package com.bfsi.egalite.entity;

public class AppParams {

	public static String DEFAULT_AGENT_LOGIN_EXPIRY_DAYS="DEFAULT AGENT LOGIN EXPIRY DAYS";
	public static String MINIMUM_MOBILE_LOGIN_PASSWORD_LENGTH="MINIMUM MOBILE LOGIN PASSWORD LENGTH";
	public static String MAXIMUM_MOBILE_LOGIN_PASSWORD_LENGTH="MAXIMUM_MOBILE_LOGIN_PASSWORD_LENGTH";
	public static String DEFAULT_DEVICE_SYNCH_BATCH_SIZE="DEFAULT DEVICE SYNCH  BATCH SIZE";
	public static String MOBILE_REGISTRATION_KEY_EXPIRATION_TIME="MOBILE REGISTRATION KEY EXPIRATION TIME";
	public static String CBS_INTERFACE_POLLING_INTERVAL_IN_SECONDS="CBS INTERFACE POLLING  INTERVAL IN SECONDS";
	public static String CBS_INTERFACE_POLLING_ENABLED="CBS INTERFACE POLLING  ENABLED";
	public static String MOBILE_REGISTRATION_KEY_LENGTH="MOBILE REGISTRATION KEY LENGTH";
	public static String NUMBERS_OF_INVALID_LOGINS="NUMBERS OF INVALID LOGINS";
	public static String MINIMUM_MOBILE_FAILED_LOGINS="MINIMUM MOBILE FAILED LOGINS";
	public static String MINIMUM_PASSWORD_LENGTH="MINIMUM PASSWORD LENGTH";
	public static String DAYS_FWD_REPAY_AGENDA="DAYS FWD REPAY AGENDA";
	public static String DAYS_FWD_DISB_AGENDA = "DAYS FWD DISB AGENDA";
	public static String HOST_NAME = "HOST NAME";
	public static String DAYS_SYNC = "DAYS SYNC";
	public static String TEMP_HOST_NAME = "TEMP HOST NAME";
	public static String INSUFFICIENT_BALANCE_OVERRIDE = "INSUFFICIENT BALANCE OVERRIDE";
	public static String NUMBERS_OF_RETRY = "NUMBERS OF RETRY";
	public static String CAN_HAV_TXN_NATV = "CAN_HAV_TXN_NATV"; 
	public static String MBS_NO_OF_PRINT = "MBS_NO_OF_PRINT";
	public static String APP_DATE_TODAY = "APP_DATE_TODAY";
	public static String ALLOW_PARTIAL_SETTLEMENT ="ALLOW_PARTIAL_SETTLEMENT";
	public static String ALLOWED_PARTIAL_PERCENT = "ALLOWED_PARTIAL_PERCENT";
	public static String USE_EXTERNAL_DEVICE = "USE_EXTERNAL_DEVICE";
}
